
package com.sforce.soap.enterprise;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soap", targetNamespace = "urn:enterprise.soap.sforce.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Soap {


    /**
     * Login to the Salesforce.com SOAP Api
     * 
     * @param parameters
     * @param loginScopeHeader
     * @return
     *     returns com.sforce.soap.enterprise.LoginResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     * @throws LoginFault_Exception
     */
    @WebMethod
    @WebResult(name = "loginResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public LoginResponse login(
        @WebParam(name = "login", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Login parameters,
        @WebParam(name = "LoginScopeHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LoginScopeHeader")
        LoginScopeHeader loginScopeHeader)
        throws InvalidIdFault_Exception, LoginFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe an sObject
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSObjectResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeSObjectResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSObjectResponse describeSObject(
        @WebParam(name = "describeSObject", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSObject parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe a number sObjects
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSObjectsResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeSObjectsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSObjectsResponse describeSObjects(
        @WebParam(name = "describeSObjects", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSObjects parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the Global state
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeGlobalResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeGlobalResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeGlobalResponse describeGlobal(
        @WebParam(name = "describeGlobal", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeGlobal parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe all the data category groups available for a given set of types
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeDataCategoryGroupsResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeDataCategoryGroupsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeDataCategoryGroupsResponse describeDataCategoryGroups(
        @WebParam(name = "describeDataCategoryGroups", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeDataCategoryGroups parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the data category group structures for a given set of pair of types and data category group name
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeDataCategoryGroupStructuresResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeDataCategoryGroupStructuresResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeDataCategoryGroupStructuresResponse describeDataCategoryGroupStructures(
        @WebParam(name = "describeDataCategoryGroupStructures", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeDataCategoryGroupStructures parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describes your Knowledge settings, such as if knowledgeEnabled is on or off, its default language and supported languages
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeKnowledgeSettingsResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeKnowledgeSettingsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeKnowledgeSettingsResponse describeKnowledgeSettings(
        @WebParam(name = "describeKnowledgeSettings", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeKnowledgeSettings parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe a list of FlexiPage and their contents
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeFlexiPagesResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeFlexiPagesResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeFlexiPagesResponse describeFlexiPages(
        @WebParam(name = "describeFlexiPages", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeFlexiPages parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the items in an AppMenu
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeAppMenuResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeAppMenuResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeAppMenuResponse describeAppMenu(
        @WebParam(name = "describeAppMenu", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeAppMenu parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe Gloal and Themes
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeGlobalThemeResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeGlobalThemeResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeGlobalThemeResponse describeGlobalTheme(
        @WebParam(name = "describeGlobalTheme", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeGlobalTheme parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe Themes
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeThemeResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeThemeResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeThemeResponse describeTheme(
        @WebParam(name = "describeTheme", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeTheme parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the layout of the given sObject or the given actionable global page.
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeLayoutResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeLayoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeLayoutResponse describeLayout(
        @WebParam(name = "describeLayout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeLayout parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the layout of the SoftPhone
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSoftphoneLayoutResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeSoftphoneLayoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSoftphoneLayoutResponse describeSoftphoneLayout(
        @WebParam(name = "describeSoftphoneLayout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSoftphoneLayout parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the search view of an sObject
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSearchLayoutsResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeSearchLayoutsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSearchLayoutsResponse describeSearchLayouts(
        @WebParam(name = "describeSearchLayouts", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSearchLayouts parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe a list of objects representing the order and scope of objects on a users search result page
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSearchScopeOrderResponse
     */
    @WebMethod
    @WebResult(name = "describeSearchScopeOrderResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSearchScopeOrderResponse describeSearchScopeOrder(
        @WebParam(name = "describeSearchScopeOrder", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSearchScopeOrder parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Describe the compact layouts of the given sObject
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeCompactLayoutsResponse
     */
    @WebMethod
    @WebResult(name = "describeCompactLayoutsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeCompactLayoutsResponse describeCompactLayouts(
        @WebParam(name = "describeCompactLayouts", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeCompactLayouts parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Describe the approval layouts of the given sObject
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeApprovalLayoutResponse
     */
    @WebMethod
    @WebResult(name = "describeApprovalLayoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeApprovalLayoutResponse describeApprovalLayout(
        @WebParam(name = "describeApprovalLayout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeApprovalLayout parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Describe the ListViews as SOQL metadata for the generation of SOQL.
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSoqlListViewsResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeSoqlListViewsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSoqlListViewsResponse describeSoqlListViews(
        @WebParam(name = "describeSoqlListViews", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSoqlListViews parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Execute the specified list view and return the presentation-ready results.
     * 
     * @param mruHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.ExecuteListViewResponse
     */
    @WebMethod
    @WebResult(name = "executeListViewResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ExecuteListViewResponse executeListView(
        @WebParam(name = "executeListView", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        ExecuteListView parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Describe the tabs that appear on a users page
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeTabsResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeTabsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeTabsResponse describeTabs(
        @WebParam(name = "describeTabs", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeTabs parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe all tabs available to a user
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeAllTabsResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "describeAllTabsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeAllTabsResponse describeAllTabs(
        @WebParam(name = "describeAllTabs", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeAllTabs parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the primary compact layouts for the sObjects requested
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribePrimaryCompactLayoutsResponse
     */
    @WebMethod
    @WebResult(name = "describePrimaryCompactLayoutsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribePrimaryCompactLayoutsResponse describePrimaryCompactLayouts(
        @WebParam(name = "describePrimaryCompactLayouts", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribePrimaryCompactLayouts parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Create a set of new sObjects
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param localeOptions
     * @param sessionHeader
     * @param disableFeedTrackingHeader
     * @param allOrNoneHeader
     * @param debuggingInfo
     * @param emailHeader
     * @param streamingEnabledHeader
     * @param assignmentRuleHeader
     * @param debuggingHeader
     * @param limitInfoHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.CreateResponse
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "createResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public CreateResponse create(
        @WebParam(name = "create", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Create parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AssignmentRuleHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AssignmentRuleHeader")
        AssignmentRuleHeader assignmentRuleHeader,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "AllOrNoneHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllOrNoneHeader")
        AllOrNoneHeader allOrNoneHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Update a set of sObjects
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param localeOptions
     * @param sessionHeader
     * @param disableFeedTrackingHeader
     * @param allOrNoneHeader
     * @param debuggingInfo
     * @param emailHeader
     * @param streamingEnabledHeader
     * @param assignmentRuleHeader
     * @param debuggingHeader
     * @param ownerChangeOptions
     * @param limitInfoHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.UpdateResponse
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "updateResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public UpdateResponse update(
        @WebParam(name = "update", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Update parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AssignmentRuleHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AssignmentRuleHeader")
        AssignmentRuleHeader assignmentRuleHeader,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "AllOrNoneHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllOrNoneHeader")
        AllOrNoneHeader allOrNoneHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "OwnerChangeOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "OwnerChangeOptions")
        OwnerChangeOptions ownerChangeOptions,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Update or insert a set of sObjects based on object id
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param localeOptions
     * @param sessionHeader
     * @param disableFeedTrackingHeader
     * @param allOrNoneHeader
     * @param debuggingInfo
     * @param emailHeader
     * @param streamingEnabledHeader
     * @param assignmentRuleHeader
     * @param debuggingHeader
     * @param ownerChangeOptions
     * @param limitInfoHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.UpsertResponse
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "upsertResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public UpsertResponse upsert(
        @WebParam(name = "upsert", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Upsert parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AssignmentRuleHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AssignmentRuleHeader")
        AssignmentRuleHeader assignmentRuleHeader,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "AllOrNoneHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllOrNoneHeader")
        AllOrNoneHeader allOrNoneHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "OwnerChangeOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "OwnerChangeOptions")
        OwnerChangeOptions ownerChangeOptions,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Merge and update a set of sObjects based on object id
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param localeOptions
     * @param sessionHeader
     * @param disableFeedTrackingHeader
     * @param debuggingInfo
     * @param emailHeader
     * @param streamingEnabledHeader
     * @param assignmentRuleHeader
     * @param debuggingHeader
     * @param limitInfoHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.MergeResponse
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "mergeResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public MergeResponse merge(
        @WebParam(name = "merge", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Merge parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AssignmentRuleHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AssignmentRuleHeader")
        AssignmentRuleHeader assignmentRuleHeader,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Delete a set of sObjects
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param disableFeedTrackingHeader
     * @param allOrNoneHeader
     * @param debuggingInfo
     * @param emailHeader
     * @param streamingEnabledHeader
     * @param debuggingHeader
     * @param limitInfoHeader
     * @param userTerritoryDeleteHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.DeleteResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "deleteResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DeleteResponse delete(
        @WebParam(name = "delete", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Delete parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "UserTerritoryDeleteHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "UserTerritoryDeleteHeader")
        UserTerritoryDeleteHeader userTerritoryDeleteHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "AllOrNoneHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllOrNoneHeader")
        AllOrNoneHeader allOrNoneHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Undelete a set of sObjects
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param disableFeedTrackingHeader
     * @param allOrNoneHeader
     * @param limitInfoHeader
     * @param debuggingInfo
     * @param streamingEnabledHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.UndeleteResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "undeleteResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public UndeleteResponse undelete(
        @WebParam(name = "undelete", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Undelete parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "AllOrNoneHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllOrNoneHeader")
        AllOrNoneHeader allOrNoneHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Empty a set of sObjects from the recycle bin
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.EmptyRecycleBinResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "emptyRecycleBinResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public EmptyRecycleBinResponse emptyRecycleBin(
        @WebParam(name = "emptyRecycleBin", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        EmptyRecycleBin parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Get a set of sObjects
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param sessionHeader
     * @param queryOptions
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.RetrieveResponse
     * @throws MalformedQueryFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "retrieveResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public RetrieveResponse retrieve(
        @WebParam(name = "retrieve", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Retrieve parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "QueryOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "QueryOptions")
        QueryOptions queryOptions,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Submit an entity to a workflow process or process a workitem
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param disableFeedTrackingHeader
     * @param limitInfoHeader
     * @param debuggingInfo
     * @param streamingEnabledHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.ProcessResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "processResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ProcessResponse process(
        @WebParam(name = "process", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Process parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * convert a set of leads
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param disableFeedTrackingHeader
     * @param limitInfoHeader
     * @param debuggingInfo
     * @param streamingEnabledHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.ConvertLeadResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "convertLeadResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ConvertLeadResponse convertLead(
        @WebParam(name = "convertLead", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        ConvertLead parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Logout the current user, invalidating the current session.
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.LogoutResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "logoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public LogoutResponse logout(
        @WebParam(name = "logout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Logout parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Logs out and invalidates session ids
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.InvalidateSessionsResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "invalidateSessionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public InvalidateSessionsResponse invalidateSessions(
        @WebParam(name = "invalidateSessions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        InvalidateSessions parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Get the IDs for deleted sObjects
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetDeletedResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "getDeletedResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetDeletedResponse getDeleted(
        @WebParam(name = "getDeleted", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetDeleted parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Get the IDs for updated sObjects
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetUpdatedResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     */
    @WebMethod
    @WebResult(name = "getUpdatedResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetUpdatedResponse getUpdated(
        @WebParam(name = "getUpdated", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetUpdated parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Create a Query Cursor
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param sessionHeader
     * @param queryOptions
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.QueryResponse
     * @throws MalformedQueryFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidQueryLocatorFault_Exception
     */
    @WebMethod
    @WebResult(name = "queryResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public QueryResponse query(
        @WebParam(name = "query", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Query parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "QueryOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "QueryOptions")
        QueryOptions queryOptions,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidQueryLocatorFault_Exception, InvalidSObjectFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Create a Query Cursor, including deleted sObjects
     * 
     * @param sessionHeader
     * @param queryOptions
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.QueryAllResponse
     * @throws MalformedQueryFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidIdFault_Exception
     * @throws InvalidQueryLocatorFault_Exception
     */
    @WebMethod
    @WebResult(name = "queryAllResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public QueryAllResponse queryAll(
        @WebParam(name = "queryAll", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        QueryAll parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "QueryOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "QueryOptions")
        QueryOptions queryOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidQueryLocatorFault_Exception, InvalidSObjectFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Gets the next batch of sObjects from a query
     * 
     * @param sessionHeader
     * @param queryOptions
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.QueryMoreResponse
     * @throws MalformedQueryFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidQueryLocatorFault_Exception
     */
    @WebMethod
    @WebResult(name = "queryMoreResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public QueryMoreResponse queryMore(
        @WebParam(name = "queryMore", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        QueryMore parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "QueryOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "QueryOptions")
        QueryOptions queryOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidQueryLocatorFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Search for sObjects
     * 
     * @param packageVersionHeader
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SearchResponse
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws MalformedSearchFault_Exception
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SearchResponse search(
        @WebParam(name = "search", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Search parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidFieldFault_Exception, InvalidSObjectFault_Exception, MalformedSearchFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Gets server timestamp
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetServerTimestampResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "getServerTimestampResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetServerTimestampResponse getServerTimestamp(
        @WebParam(name = "getServerTimestamp", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetServerTimestamp parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Set a user's password
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SetPasswordResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidNewPasswordFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "setPasswordResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SetPasswordResponse setPassword(
        @WebParam(name = "setPassword", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        SetPassword parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidIdFault_Exception, InvalidNewPasswordFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Reset a user's password
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param emailHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.ResetPasswordResponse
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "resetPasswordResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ResetPasswordResponse resetPassword(
        @WebParam(name = "resetPassword", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        ResetPassword parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Returns standard information relevant to the current user
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetUserInfoResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "getUserInfoResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetUserInfoResponse getUserInfo(
        @WebParam(name = "getUserInfo", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetUserInfo parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Send existing draft EmailMessage
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SendEmailMessageResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "sendEmailMessageResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SendEmailMessageResponse sendEmailMessage(
        @WebParam(name = "sendEmailMessage", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        SendEmailMessage parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Send outbound email
     * 
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SendEmailResponse
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "sendEmailResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SendEmailResponse sendEmail(
        @WebParam(name = "sendEmail", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        SendEmail parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Perform a series of predefined actions such as quick create or log a task
     * 
     * @param packageVersionHeader
     * @param mruHeader
     * @param localeOptions
     * @param sessionHeader
     * @param disableFeedTrackingHeader
     * @param allOrNoneHeader
     * @param emailHeader
     * @param streamingEnabledHeader
     * @param assignmentRuleHeader
     * @param debuggingHeader
     * @param ownerChangeOptions
     * @param limitInfoHeader
     * @param parameters
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.enterprise.PerformQuickActionsResponse
     */
    @WebMethod
    @WebResult(name = "performQuickActionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public PerformQuickActionsResponse performQuickActions(
        @WebParam(name = "performQuickActions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        PerformQuickActions parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "AssignmentRuleHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AssignmentRuleHeader")
        AssignmentRuleHeader assignmentRuleHeader,
        @WebParam(name = "MruHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "MruHeader")
        MruHeader mruHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DisableFeedTrackingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DisableFeedTrackingHeader")
        DisableFeedTrackingHeader disableFeedTrackingHeader,
        @WebParam(name = "StreamingEnabledHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "StreamingEnabledHeader")
        StreamingEnabledHeader streamingEnabledHeader,
        @WebParam(name = "AllOrNoneHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "AllOrNoneHeader")
        AllOrNoneHeader allOrNoneHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "EmailHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "EmailHeader")
        EmailHeader emailHeader,
        @WebParam(name = "OwnerChangeOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "OwnerChangeOptions")
        OwnerChangeOptions ownerChangeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Describe the details of a series of quick actions
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeQuickActionsResponse
     */
    @WebMethod
    @WebResult(name = "describeQuickActionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeQuickActionsResponse describeQuickActions(
        @WebParam(name = "describeQuickActions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeQuickActions parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Describe the details of a series of quick actions available for the given contextType
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeAvailableQuickActionsResponse
     */
    @WebMethod
    @WebResult(name = "describeAvailableQuickActionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeAvailableQuickActionsResponse describeAvailableQuickActions(
        @WebParam(name = "describeAvailableQuickActions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeAvailableQuickActions parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

    /**
     * Retreive the template sobjects, if appropriate, for the given quick action names in a given context
     * 
     * @param packageVersionHeader
     * @param localeOptions
     * @param sessionHeader
     * @param limitInfoHeader
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.RetrieveQuickActionTemplatesResponse
     */
    @WebMethod
    @WebResult(name = "retrieveQuickActionTemplatesResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public RetrieveQuickActionTemplatesResponse retrieveQuickActionTemplates(
        @WebParam(name = "retrieveQuickActionTemplates", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        RetrieveQuickActionTemplates parameters,
        @WebParam(name = "SessionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "PackageVersionHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "PackageVersionHeader")
        PackageVersionHeader packageVersionHeader,
        @WebParam(name = "LocaleOptions", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, partName = "LocaleOptions")
        LocaleOptions localeOptions,
        @WebParam(name = "LimitInfoHeader", targetNamespace = "urn:enterprise.soap.sforce.com", header = true, mode = WebParam.Mode.OUT, partName = "LimitInfoHeader")
        Holder<LimitInfoHeader> limitInfoHeader);

}
